package com.archive.ui.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * ============================================================================
 * ENTITY: UserLayout
 * ============================================================================
 * WHAT IT DOES:
 * Persists Dockview window arrangements and APEX command bar preferences.
 *
 * WHY IT IS USED:
 * Allows users to customize multi-panel "War Room" workspaces (e.g. "OPS", "READ",
 * "WAR") and configure the Command Bar position to TOP or BOTTOM.
 *
 * SYNTAX BREAKDOWN:
 * - layoutName: Unique identifier for the layout preset (e.g., "OPS", "READ", "default").
 * - layoutJson: The serialized JSON tree generated by Dockview's toJSON() API.
 * - commandBarPosition: Stores the user's preference for bar placement ("TOP" or "BOTTOM").
 * ============================================================================
 */
@Entity
@Table(name = "user_layout")
@Getter
@Setter
@NoArgsConstructor
public class UserLayout {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "uuid", columnDefinition = "UUID", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "layout_name", nullable = false, unique = true)
    private String layoutName;

    @Column(name = "layout_json", nullable = false, columnDefinition = "TEXT")
    private String layoutJson;

    @Column(name = "command_bar_position", nullable = false)
    private String commandBarPosition = "TOP";

    @CreationTimestamp
    @Column(name = "date_created", updatable = false, columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime dateCreated;

    @UpdateTimestamp
    @Column(name = "last_updated", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime lastUpdated;

    public UserLayout(String layoutName, String layoutJson, String commandBarPosition) {
        this.layoutName = layoutName;
        this.layoutJson = layoutJson;
        this.commandBarPosition = (commandBarPosition != null) ? commandBarPosition.toUpperCase() : "TOP";
    }
}
